[package]
name = "onion-spider"
version = "0.1.0"
authors = ["Dan Rammer <hamersaw@gmail.com>"]
build = "build.rs"

[build-dependencies]
capnpc = "0.7.*"

[dependencies]
capnp = "0.7.*"
capnpc = "0.7.*"
docopt = "0.6.*"
glob = "0.2.*"
regex = "*"
rustc-serialize = "0.3.*"
